package CampusServerApp;


/**
* Corba/CampusServerApp/CampusServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 29, 2021 3:13:20 o'clock PM EDT
*/

abstract public class CampusServerHelper
{
  private static String  _id = "IDL:Corba/CampusServerApp/CampusServer:1.0";

  public static void insert (org.omg.CORBA.Any a, CampusServerApp.CampusServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CampusServerApp.CampusServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CampusServerApp.CampusServerHelper.id (), "CampusServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CampusServerApp.CampusServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CampusServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CampusServerApp.CampusServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CampusServerApp.CampusServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CampusServerApp.CampusServer)
      return (CampusServerApp.CampusServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CampusServerApp._CampusServerStub stub = new CampusServerApp._CampusServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CampusServerApp.CampusServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CampusServerApp.CampusServer)
      return (CampusServerApp.CampusServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CampusServerApp._CampusServerStub stub = new CampusServerApp._CampusServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
