package CampusServerApp;


/**
* Corba/CampusServerApp/CampusServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 29, 2021 3:13:20 o'clock PM EDT
*/

public interface CampusServerOperations 
{
  String getAvailableTimeSlot (CampusServerApp.Date date, String id);
  String bookRoom (CampusServerApp.Campus campusName, int roomNumber, CampusServerApp.Date date, CampusServerApp.TimeSlot timeSlot, String id);
  String cancelBooking (String bookingID, String id);
  String createRoom (int roomNumber, CampusServerApp.Date date, CampusServerApp.TimeSlot[] timeSlotSet, String id);
  String deleteRoom (int roomNumber, CampusServerApp.Date date, CampusServerApp.TimeSlot[] timeSlotSet, String id);
} // interface CampusServerOperations
