package CampusServerApp;


/**
* Corba/CampusServerApp/CampusServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 29, 2021 3:13:20 o'clock PM EDT
*/

public interface CampusServer extends CampusServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CampusServer
