package CampusServerApp;


/**
* Corba/CampusServerApp/RoomRecord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 29, 2021 3:13:20 o'clock PM EDT
*/

public final class RoomRecord implements org.omg.CORBA.portable.IDLEntity
{
  public CampusServerApp.Date date = null;
  public int roomNumber = (int)0;
  public CampusServerApp.TimeSlot timeSlot = null;
  public String roomRecordId = null;
  public String bookedBy = null;
  public String bookingId = null;

  public RoomRecord ()
  {
  } // ctor

  public RoomRecord (CampusServerApp.Date _date, int _roomNumber, CampusServerApp.TimeSlot _timeSlot, String _roomRecordId, String _bookedBy, String _bookingId)
  {
    date = _date;
    roomNumber = _roomNumber;
    timeSlot = _timeSlot;
    roomRecordId = _roomRecordId;
    bookedBy = _bookedBy;
    bookingId = _bookingId;
  } // ctor

} // class RoomRecord
