package CampusServerApp;


/**
* Corba/CampusServerApp/Time.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 29, 2021 3:13:20 o'clock PM EDT
*/

public final class Time implements org.omg.CORBA.portable.IDLEntity
{
  public int hour = (int)0;
  public int minute = (int)0;

  public Time ()
  {
  } // ctor

  public Time (int _hour, int _minute)
  {
    hour = _hour;
    minute = _minute;
  } // ctor

} // class Time
