package CampusServerApp;


/**
* Corba/CampusServerApp/TimeSlotSetHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 29, 2021 3:13:20 o'clock PM EDT
*/

public final class TimeSlotSetHolder implements org.omg.CORBA.portable.Streamable
{
  public CampusServerApp.TimeSlot value[] = null;

  public TimeSlotSetHolder ()
  {
  }

  public TimeSlotSetHolder (CampusServerApp.TimeSlot[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CampusServerApp.TimeSlotSetHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CampusServerApp.TimeSlotSetHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CampusServerApp.TimeSlotSetHelper.type ();
  }

}
