package CampusServerApp;

/**
* Corba/CampusServerApp/TimeSlotHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 29, 2021 3:13:20 o'clock PM EDT
*/

public final class TimeSlotHolder implements org.omg.CORBA.portable.Streamable
{
  public CampusServerApp.TimeSlot value = null;

  public TimeSlotHolder ()
  {
  }

  public TimeSlotHolder (CampusServerApp.TimeSlot initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CampusServerApp.TimeSlotHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CampusServerApp.TimeSlotHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CampusServerApp.TimeSlotHelper.type ();
  }

}
