module Corba{
    module CampusServerApp {

        struct Date {
            short year;
            short month;
            short day;
        };

        struct Time {
            short hour;
            short minute;
        };

        struct TimeSlot {
            Time start;
            Time end;
        };

        struct RoomRecord {
            Date date;
            short roomNumber;
            TimeSlot timeSlot;
            string roomRecordId;
            string bookedBy;
            string bookingId;

        };

        enum Campus { KKL, WST, DVL };

        typedef sequence<TimeSlot> TimeSlotSet;

        interface CampusServer {

            string getAvailableTimeSlot(in Date date, in string id);

            string bookRoom(in Campus campusName, in short roomNumber, in Date date, in TimeSlot timeSlot, in string id);

            string cancelBooking(in string bookingID, in string id);

            string createRoom(in short roomNumber, in Date date, in TimeSlotSet timeSlotSet, in string id);

            string deleteRoom(in short roomNumber, in Date date, in TimeSlotSet timeSlotSet, in string id);
        };

    };
};