package Corba.CampusServerApp;


/**
* Corba/CampusServerApp/Campus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 7:27:23 o'clock PM EDT
*/

public class Campus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static Corba.CampusServerApp.Campus[] __array = new Corba.CampusServerApp.Campus [__size];

  public static final int _KKL = 0;
  public static final Corba.CampusServerApp.Campus KKL = new Corba.CampusServerApp.Campus(_KKL);
  public static final int _WST = 1;
  public static final Corba.CampusServerApp.Campus WST = new Corba.CampusServerApp.Campus(_WST);
  public static final int _DVL = 2;
  public static final Corba.CampusServerApp.Campus DVL = new Corba.CampusServerApp.Campus(_DVL);

  public int value ()
  {
    return __value;
  }

  public static Corba.CampusServerApp.Campus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Campus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Campus
