package CampusServerApp;


/**
* CampusServerApp/CampusServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 3:37:47 o'clock PM EDT
*/

public interface CampusServerOperations 
{
  String getAvailableTimeSlot (CampusServerApp.Date date, String id);
  CampusServerApp.RoomRecord bookRoom (CampusServerApp.Campus campusName, short roomNumber, CampusServerApp.Date date, CampusServerApp.TimeSlot timeSlot, String id);
  CampusServerApp.RoomRecord cancelBooking (String bookingID, String id);
  String createRoom (short roomNumber, CampusServerApp.Date date, CampusServerApp.TimeSlot[] timeSlotSet, String id);
  String deleteRoom (short roomNumber, CampusServerApp.Date date, CampusServerApp.TimeSlot[] timeSlotSet, String id);
} // interface CampusServerOperations
