package Corba.CampusServerApp;


/**
* Corba/CampusServerApp/CampusServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 7:27:23 o'clock PM EDT
*/

public abstract class CampusServerPOA extends org.omg.PortableServer.Servant
 implements Corba.CampusServerApp.CampusServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getAvailableTimeSlot", new java.lang.Integer (0));
    _methods.put ("bookRoom", new java.lang.Integer (1));
    _methods.put ("cancelBooking", new java.lang.Integer (2));
    _methods.put ("createRoom", new java.lang.Integer (3));
    _methods.put ("deleteRoom", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Corba/CampusServerApp/CampusServer/getAvailableTimeSlot
       {
         Corba.CampusServerApp.Date date = Corba.CampusServerApp.DateHelper.read (in);
         String id = in.read_string ();
         String $result = null;
         $result = this.getAvailableTimeSlot (date, id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Corba/CampusServerApp/CampusServer/bookRoom
       {
         Corba.CampusServerApp.Campus campusName = Corba.CampusServerApp.CampusHelper.read (in);
         short roomNumber = in.read_short ();
         Corba.CampusServerApp.Date date = Corba.CampusServerApp.DateHelper.read (in);
         Corba.CampusServerApp.TimeSlot timeSlot = Corba.CampusServerApp.TimeSlotHelper.read (in);
         String id = in.read_string ();
         String $result = null;
         $result = this.bookRoom (campusName, roomNumber, date, timeSlot, id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // Corba/CampusServerApp/CampusServer/cancelBooking
       {
         String bookingID = in.read_string ();
         String id = in.read_string ();
         String $result = null;
         $result = this.cancelBooking (bookingID, id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Corba/CampusServerApp/CampusServer/createRoom
       {
         short roomNumber = in.read_short ();
         Corba.CampusServerApp.Date date = Corba.CampusServerApp.DateHelper.read (in);
         Corba.CampusServerApp.TimeSlot timeSlotSet[] = Corba.CampusServerApp.TimeSlotSetHelper.read (in);
         String id = in.read_string ();
         String $result = null;
         $result = this.createRoom (roomNumber, date, timeSlotSet, id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // Corba/CampusServerApp/CampusServer/deleteRoom
       {
         short roomNumber = in.read_short ();
         Corba.CampusServerApp.Date date = Corba.CampusServerApp.DateHelper.read (in);
         Corba.CampusServerApp.TimeSlot timeSlotSet[] = Corba.CampusServerApp.TimeSlotSetHelper.read (in);
         String id = in.read_string ();
         String $result = null;
         $result = this.deleteRoom (roomNumber, date, timeSlotSet, id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Corba/CampusServerApp/CampusServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CampusServer _this() 
  {
    return CampusServerHelper.narrow(
    super._this_object());
  }

  public CampusServer _this(org.omg.CORBA.ORB orb) 
  {
    return CampusServerHelper.narrow(
    super._this_object(orb));
  }


} // class CampusServerPOA
