package Corba.CampusServerApp;

/**
* Corba/CampusServerApp/CampusServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 7:27:23 o'clock PM EDT
*/

public final class CampusServerHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.CampusServerApp.CampusServer value = null;

  public CampusServerHolder ()
  {
  }

  public CampusServerHolder (Corba.CampusServerApp.CampusServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.CampusServerApp.CampusServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.CampusServerApp.CampusServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.CampusServerApp.CampusServerHelper.type ();
  }

}
