package Corba.CampusServerApp;


/**
* Corba/CampusServerApp/CampusServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 7:27:23 o'clock PM EDT
*/

public interface CampusServerOperations 
{
  String getAvailableTimeSlot (Corba.CampusServerApp.Date date, String id);
  String bookRoom (Corba.CampusServerApp.Campus campusName, short roomNumber, Corba.CampusServerApp.Date date, Corba.CampusServerApp.TimeSlot timeSlot, String id);
  String cancelBooking (String bookingID, String id);
  String createRoom (short roomNumber, Corba.CampusServerApp.Date date, Corba.CampusServerApp.TimeSlot[] timeSlotSet, String id);
  String deleteRoom (short roomNumber, Corba.CampusServerApp.Date date, Corba.CampusServerApp.TimeSlot[] timeSlotSet, String id);
} // interface CampusServerOperations
