package CampusServerApp;

/**
* CampusServerApp/DateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 3:37:47 o'clock PM EDT
*/

public final class DateHolder implements org.omg.CORBA.portable.Streamable
{
  public CampusServerApp.Date value = null;

  public DateHolder ()
  {
  }

  public DateHolder (CampusServerApp.Date initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CampusServerApp.DateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CampusServerApp.DateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CampusServerApp.DateHelper.type ();
  }

}
