package CampusServerApp;


/**
* CampusServerApp/Date.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 3:37:47 o'clock PM EDT
*/

public final class Date implements org.omg.CORBA.portable.IDLEntity
{
  public short year = (short)0;
  public short month = (short)0;
  public short day = (short)0;

  public Date ()
  {
  } // ctor

  public Date (short _year, short _month, short _day)
  {
    year = _year;
    month = _month;
    day = _day;
  } // ctor

} // class Date
