package Corba.CampusServerApp;

/**
* Corba/CampusServerApp/DateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 7:27:23 o'clock PM EDT
*/

public final class DateHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.CampusServerApp.Date value = null;

  public DateHolder ()
  {
  }

  public DateHolder (Corba.CampusServerApp.Date initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.CampusServerApp.DateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.CampusServerApp.DateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.CampusServerApp.DateHelper.type ();
  }

}
