package Corba.CampusServerApp;


/**
* Corba/CampusServerApp/RoomRecordHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 7:27:23 o'clock PM EDT
*/

abstract public class RoomRecordHelper
{
  private static String  _id = "IDL:Corba/CampusServerApp/RoomRecord:1.0";

  public static void insert (org.omg.CORBA.Any a, Corba.CampusServerApp.RoomRecord that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Corba.CampusServerApp.RoomRecord extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = Corba.CampusServerApp.DateHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "date",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[1] = new org.omg.CORBA.StructMember (
            "roomNumber",
            _tcOf_members0,
            null);
          _tcOf_members0 = Corba.CampusServerApp.TimeSlotHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "timeSlot",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "roomRecordId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "bookedBy",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "bookingId",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Corba.CampusServerApp.RoomRecordHelper.id (), "RoomRecord", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Corba.CampusServerApp.RoomRecord read (org.omg.CORBA.portable.InputStream istream)
  {
    Corba.CampusServerApp.RoomRecord value = new Corba.CampusServerApp.RoomRecord ();
    value.date = Corba.CampusServerApp.DateHelper.read (istream);
    value.roomNumber = istream.read_short ();
    value.timeSlot = Corba.CampusServerApp.TimeSlotHelper.read (istream);
    value.roomRecordId = istream.read_string ();
    value.bookedBy = istream.read_string ();
    value.bookingId = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Corba.CampusServerApp.RoomRecord value)
  {
    Corba.CampusServerApp.DateHelper.write (ostream, value.date);
    ostream.write_short (value.roomNumber);
    Corba.CampusServerApp.TimeSlotHelper.write (ostream, value.timeSlot);
    ostream.write_string (value.roomRecordId);
    ostream.write_string (value.bookedBy);
    ostream.write_string (value.bookingId);
  }

}
