package CampusServerApp;


/**
* CampusServerApp/TimeSlotSetHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 3:37:47 o'clock PM EDT
*/

abstract public class TimeSlotSetHelper
{
  private static String  _id = "IDL:CampusServerApp/TimeSlotSet:1.0";

  public static void insert (org.omg.CORBA.Any a, CampusServerApp.TimeSlot[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CampusServerApp.TimeSlot[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = CampusServerApp.TimeSlotHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CampusServerApp.TimeSlotSetHelper.id (), "TimeSlotSet", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CampusServerApp.TimeSlot[] read (org.omg.CORBA.portable.InputStream istream)
  {
    CampusServerApp.TimeSlot value[] = null;
    int _len0 = istream.read_long ();
    value = new CampusServerApp.TimeSlot[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = CampusServerApp.TimeSlotHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CampusServerApp.TimeSlot[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      CampusServerApp.TimeSlotHelper.write (ostream, value[_i0]);
  }

}
