package Corba.CampusServerApp;


/**
* Corba/CampusServerApp/TimeSlot.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 7:27:23 o'clock PM EDT
*/

public final class TimeSlot implements org.omg.CORBA.portable.IDLEntity
{
  public Corba.CampusServerApp.Time start = null;
  public Corba.CampusServerApp.Time end = null;

  public TimeSlot ()
  {
  } // ctor

  public TimeSlot (Corba.CampusServerApp.Time _start, Corba.CampusServerApp.Time _end)
  {
    start = _start;
    end = _end;
  } // ctor

} // class TimeSlot
