package Corba.CampusServerApp;

/**
* Corba/CampusServerApp/TimeSlotHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 7:27:23 o'clock PM EDT
*/

public final class TimeSlotHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.CampusServerApp.TimeSlot value = null;

  public TimeSlotHolder ()
  {
  }

  public TimeSlotHolder (Corba.CampusServerApp.TimeSlot initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.CampusServerApp.TimeSlotHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.CampusServerApp.TimeSlotHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.CampusServerApp.TimeSlotHelper.type ();
  }

}
