package CampusServerApp;

/**
* CampusServerApp/TimeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CampusServer.idl
* Friday, October 22, 2021 3:37:47 o'clock PM EDT
*/

public final class TimeHolder implements org.omg.CORBA.portable.Streamable
{
  public CampusServerApp.Time value = null;

  public TimeHolder ()
  {
  }

  public TimeHolder (CampusServerApp.Time initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CampusServerApp.TimeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CampusServerApp.TimeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CampusServerApp.TimeHelper.type ();
  }

}
